### ISSUE TITLE
3월 목표

### ISSUE THREAD

**Issue by currenjin** [currenjin/site-for-developers#49]

**Comment by currenjin** [comment]
3월 목표를 가시화하기 위한 이슈입니다! @rivercory

**Comment by currenjin** [comment]
시간날 때 적어볼게요 요즘 너무 바빠서 여유가 없네요 ㅠㅠ

**Comment by rivercory** [comment]
@currenjin 3월달엔 모바일 대응 및 데이터 대랑 추가 등의 작입을 하는건 어떨가요?

**Comment by rivercory** [comment]
@currenjin 또한 커뮤니티를 활성화 (디스코드, 문의하기 등) 하여 더 많은 의견을 들어보고자 합니다!

**Comment by currenjin** [comment]
일을 끝내고 오니,, 3월이 끝나가 있었다..

**Comment by currenjin** [comment]
너무 바빴던 한 달이었습니다 죄송해요 ㅠㅠ

**Comment by currenjin** [comment]
갔다온 사이에 스타 수가 많이 늘었네요!

**Comment by rivercory** [comment]
200 stars 축하합니다 🎉
일단 이 목표는 4월로 연기하는 것이 좋겠네요!
이미지 추가는 최대한 빨리 처리하겠습니다.

**Comment by rivercory** [comment]
다만 4월달엔 저도 활동을 잘 못할 것 같네요 (중간고사) 😢

**Comment by currenjin** [comment]
으억 ㅠㅠ 갔다 오시는 동안 열심히 해놓겠습니다!

**Comment by currenjin** [comment]
함께 좋은 정보를 많은 사람들에게 나누는 과정이 좋네요 :D 감사합니다 항상 현호 님!

**Comment by currenjin** [comment]
해당 이슈는 클로즈 할게요 ㅋㅋ
