### ISSUE TITLE
웹사이트 내 목차 이동 불가

### ISSUE THREAD

**Issue by currenjin** [currenjin/site-for-developers#9]
https://site-for-developers.vercel.app/

Hash값이 붙지만, 목차에 해당하는 카테고리로 이동이 불가함

**Comment by currenjin** [comment]
@hyeonho2010 이곳에서 해당 이슈 기록해나가면 좋을 것 같아요!

**Comment by hyeonho2010** [comment]
@currenjin 네😊
일단 임시로 웹사이트에서 목차를 표시하지 않는 코드를 넣어놨는데 어떻게 생각하시나요?
추후 문제가 생기면 다시 표시할 예정입니다 :)

https://github.com/hyeonho2010/site-for-developers/commit/e7a9d4c02599c9d64864e034692631a359f1edf9

**Comment by currenjin** [comment]
@hyeonho2010 좋은 아이디어입니다.

하지만 저는 보여주는 상태가 낫다라고 생각하는게,

1. 사람들이 어떤 내용이 있는지 미리 확인할 수 있다.
2. 클릭이 안 되는 상황에서 누군가가 문제를 느끼고 PR을 올려줄 수 있다.

크리티컬한 문제가 아니기 때문에 위 의견이 도출되더라구요!

어떻게 생각하시나요?

**Comment by currenjin** [comment]
혹은 목차를 클릭할 수 없는 형태로 만드는 것도 방법이겠네요! 편하게 의견 주세용

**Comment by hyeonho10** [comment]
@currenjin 알겠습니다 :)
의견을 반영해서 목차 부분을 표시하겠으나 상단에 배너를 표시해서 오류가 발생한다는 것을 충분히 공지하겠습니다!

**Comment by currenjin** [comment]
감사합니다!

**Comment by hyeonho2010** [comment]
@currenjin 목차를 클릭할 수 없는 오류가 markdown 형식에서 html 형식으로 바뀌기 때문에 기존 Hash값을 해석하지 못하는거 같아요...
markdown에서 html을 사용할 수 있으니까 그 부분을 이용해서 수정해보는 걸 고민해보는 중이에요!

**Comment by hyeonho10** [comment]
@currenjin 다만 우려되는 점이 이 문제가 마크다운 & html 호환성 문제이다 보니까 마크다운에서 다른 요소가 추가되었을때에 비슷한 문제가 발생할 수 있단 점이에요...

**Comment by currenjin** [comment]
아니면 showdown이라는 library를 사용해보는 건 어떠세요?
https://github.com/showdownjs/showdown

**Comment by hyeonho10** [comment]
@currenjin 주말에는 이 이슈 중심적으로 해결해보겠습니다👍🏻 조언 감사합니다!
